<div class="seller-footer-main">
	<div class="container">
	<div class="row">
	<div class="col-md-6 col-12">
	<div class="footer-info-link">
	<ul>
	<li><a href="#">Terms &amp; Conditions</a></li>
	<li><a href="#">Privacy Policy</a></li>
	<li><a href="#">Help &amp; Support</a></li>
	</ul>
	</div>
	</div>
	<div class="col-md-6 col-12">
	<div class="support-link-seller">
	<p>Still have questions? Visit our <a href="#">Support Center for sellers</a></p>
	</div>
	</div>
	</div>
	</div>
</div>
<div class="copy-right-seller">
<p>© 2021 - QaderExpress TM - All rights reserved</p>
</div>



		<script type="text/javascript">
	require(['jquery','bootstrap']);
</script>






<script type="text/javascript">
require(['jquery','owlcarousel3'],function(jQuery){
	
	
			jQuery(document).ready(function(){ 
			
					jQuery('.hero-slider').owlCarousel({
						loop: true,
						nav: true,
						dots: false,
						autoplay: true,
						lazyLoad: true,
						autoplaySpeed: 3000,
						paginationSpeed: 3000,
						autoplayTimeout: 3000,
						responsive: {

							320: {
								items: 1
							},

							580: {
								items: 1
							},
							768: {
								items: 1
							},
							1000: {
								items: 1
							}
						}
					});
													
					jQuery('.navbar-toggler').click(function(){
						jQuery(this).toggleClass('collapsed');
					});
			});
    });
</script>





