<section class="media-gallery">
    <div class="gallerybanner-img">
        <img src="/media/gallery/galry-banner.jpg" alt="">
        <div class="topBanner-text">
            <h1>Career</h1>
            <p>Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type.</p>
        </div>
    </div>
</section>

<section class="career">
    <div class="container">
        <div class="row">
            <?php $careerBlock = $block->getLayout()->createBlock('Etail\Career\Block\Index\Detail')?>
            <?php foreach($careerBlock->careerList() as $career):?>
            <div class="col-lg-4 col-md-4 col-sm-12">
                <div class="career-list">
                    <h2><?= $career->getName()?></h2>
                    <!-- <h3>Business Development</h3> -->
                    <p class="textcolor"><?= $career->getAddress()?></p>
                    <div class="candidates-apply-btn">
                        <a href="<?= $block->getBaseUrl()."careers/".$career->getUrlKey()?>">Apply</a>
                    </div>
                </div>

            </div>
            <?php endforeach?>

        </div>
    </div>
</section>

<style>
    .gallerybanner-img img {
        width: 100%;
        display: block;
    }

    .topBanner-text {
        position: absolute;
        top: 50%;
        left: 50%;
        transform: translate(-50%, -50%);
    }
    .topBanner-text > p {
        display: none;
    }

    section.media-gallery {
        position: relative;
        margin-bottom: 40px;
    }

    section.media-gallery:after {
        content: "";
        display: block;
        position: absolute;
        top: 0;
        left: 0;
        height: 100%;
        width: 100%;
        background: linear-gradient(to bottom, rgba(0, 0, 0, .40) 0%, rgba(0, 0, 0, .40) 100%);
    }

    .topBanner-text h1 {
        font-weight: 600;
        font-size: 39px;
        padding: 0;
        text-transform: uppercase;
        margin-bottom: 20px;
        text-align: center;
        color: #0d4c26;
        line-height: 36px;
    }

    .topBanner-text p {
        font-size: 17px;
        color: #000;
        margin-bottom: 20px;
        text-align: center;
    }

    .career-list {
        background: #f1f1f1;
        padding-top: 20px;
        padding-bottom: 20px;
        min-height: 265px;
        border-radius: 5px;
    }

    .career-list h2,
    .career-list h3,
    .career-list p {
        text-align: center;
    }

    .career-list h2 {
        font-size: 20px;
        text-transform: uppercase;
        margin-bottom: 15px;
        margin-top: 20px;
        color: #222;
    }

    .career-list h3 {
        font-size: 15px;
        margin-bottom: 5px;
        color: #222;
    }

    .career-list p.textcolor {
        font-size: 13px;
        color: #000;
        line-height: 21px;
    }

    .cms-career .breadcrumbs {
        display: none;
    }

    .career .row {
        margin: 0 -10px;
    }

    .career .row {
        margin: 0px -10px;
    }

    .career [class*=" col-"] {
        padding: 0px 10px;
        margin-bottom: 20px;
    }

    .candidates-apply-btn a {
        padding: 10px 36px;
        font-size: 13px;
        display: inline-block;
        text-align: center;
        border: 1px solid #222;
        color: #222;
        line-height: 15px;
        text-transform: uppercase;
        border-radius: 5px;
    }

    .candidates-apply-btn {
        text-align: center;
        margin-top: 15px;
    }

    .candidates-apply-btn a:hover {
        background: #f1f1f1;
    }


    @media (max-width:767px) {
        .columns .column.main {
            padding: 0 0px;
        }

        .topBanner-text {
            position: static;
            top: 0;
            left: unset;
            transform: unset;
            padding: 2% 1%;
        }

        .topBanner-text h1 {
            font-size: 26px;
            margin-bottom: 5px;
            line-height: 24px;
            margin-top: 10px;
        }

        .topBanner-text p {
            font-size: 15px;
            margin-bottom: 10px;
        }

        section.media-gallery:after {
            display: none;
        }

        .career-list { 
            min-height: 245px; 
        }

    }
</style>
