<section class="career-details">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <h2>Director of Strategic Alliances</h2>
                <p class="conpany_name m-0">at Pivot <a href="#">(View all jobs)</a></p>
                <p class="location m-0">Redwood City, CA, Remote</p>
                <h4 class="my-4">Together, we will save millions of lives.</h4>
                <p class="mb-4">Pivot is a digital health company delivering clinically-proven solutions that empower people to take control of their health. Named to Fast Company’s prestigious annual list of the World’s Most Innovative Companies for 2020, the
                    Pivot brand is an industry leader in tobacco and vaping cessation. Combining behavioral science, proprietary FDA-cleared medical device technology, pharmacotherapy, community support, and dedicated coaching, we aim to help
                    millions of people quit tobacco. We are growing fast. Join us. Learn more at https://pivot.co.</p>
                <h4 class="mb-4">Description</h4>
                <p class="mb-4">Pivot is a digital health company delivering clinically-proven solutions that empower people to take control of their health. Named to Fast Company’s prestigious annual list of the World’s Most Innovative Companies for 2020, the
                    Pivot brand is an industry leader in tobacco and vaping cessation. Combining behavioral science, proprietary FDA-cleared medical device technology, pharmacotherapy, community support, and dedicated coaching, we aim to help
                    millions of people quit tobacco. We are growing fast. Join us. Learn more at https://pivot.co.</p>
                <h4 class="mb-4">What you’ll be doing</h4>
                <ul class="What_list">
                    <li>Be a key driver in the expansion of Pivot as the best-in-class digital smoking cessation program with a mission to help millions of people quit smoking</li>
                    <li>Take ownership of strategy and execution of Pivot’s growth via B2B platform partnerships - developing win-win partnerships to grow Pivot business beyond direct sales.</li>
                    <li>Identify key opportunities for growth and success of partnerships, and test and learn to maximize them. Develop best practices for working with partners that can be replicated as you grow the team to serve an expanding set
                        of partners.</li>
                    <li>Identify and develop strong champion/s for Pivot within partners to increase awareness and advocacy of Pivot by their sales and marketing teams. Collaborate to create incentives for partners to compel sell-through of Pivot.</li>
                    <li>Collaborate with Pivot Sales team to coordinate approach to building and managing partner client pipeline. </li>
                    <li>Collaborate with all functional areas of Pivot to ensure our marketing, product, reporting and business operations function optimally to serve our partnerships. </li>
                    <li>Conduct regular business reviews with partners to assess progress against goals and identify areas for further partnership</li>
                    <li>Lead strategy and process for bringing on new platform partners - prioritize potential partners based on joint interests / clients, operational simplicity/complexity, and potential value to the business. Create compelling joint
                        value propositions for partnership opportunities based on partner strengths, understand and articulate how Pivot can advance their mission and grow their business.</li>
                </ul>
                <h4 class="mb-4">What you should have</h4>
                <ul class="What_list_num">
                    <li>At least 3 years in a leadership role managing platform / channel partnerships selling to enterprise buyers (ideally to health care / employee benefits buyers).</li>
                    <li>7+ years of experience in Sales, Account Management, Marketing, Product, Benefit Consulting, or Platform/Channel roles.</li>
                    <li>Experience with digital health, employee benefit programs, and/or software for healthcare applications.</li>
                    <li>Relationship developer, team player who will seek out and find success for both Pivot and partners for win-win solutions.</li>
                    <li>Highly organized, strategic thinker who can develop strategies, outline requirements and measure results.</li>
                    <li>Has a combination of sales, creative ideation, and team and project management skills to develop and test programs, iterate and expand.</li>
                    <li>Ability to develop business cases (qualitative and quantitative) to drive prioritization decisions and inspire teams to deliver on projects. </li>
                    <li>Excellent documentation and communication skills to keep teams and stakeholders aligned.</li>
                    <li>Experience leading cross-functional projects and teams.</li>
                    <li>Bachelor’s degree, MBA preferred.</li>
                </ul>
                <h4 class="mb-4">Reports to</h4>
                <p class="mb-4">SVP, Corporate Development </p>
                <h4 class="mb-4">What we offer</h4>
                <p class="mb-4">At Pivot, we'll take care of you. In addition to competitive salaries, challenging work assignments, and developmental opportunities, we offer medical, dental and vision insurance, stock options, baby bonding leave and generous
                    PTO, including dedicated time for volunteering. </p>
                <p class="mb-4">A passionate, values-driven, supportive team, solving a huge healthcare problem that can change lives. Opportunity to get on the ground floor of a fast growing digital health company, working with some of America’s largest health
                    plans and corporations.</p>
                <p class="mb-4">We are an equal opportunity employer and value diversity at our company. We do not discriminate on the basis of race, religion, color, national origin, gender, sexual orientation, age, marital status, veteran status, or disability
                    status.
                </p>
            </div>
        </div>
    </div>


    <div class="carrerDetails-form">
        <div class="container">
            <h4 class="mb-4">Fill in the Details</h4>
            <div class="p-4 bg-info">
                <form action="">
                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                <label class="text-white" for="Firstname">First name</label>
                                <input type="text" class="form-control">
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                <label class="text-white" for="lastname">Last name</label>
                                <input type="text" class="form-control">
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                <label class="text-white" for="inputEmail4">Email</label>
                                <input type="email" class="form-control" id="inputEmail4" placeholder="Email">
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                <label class="text-white" for="inputPhone">Phone</label>
                                <input type="text" class="form-control" id="inputPhone">
                            </div>
                        </div>
                        <div class="col-md-12">
                            <div class="form-group">
                                <label class="text-white" for="inputCity">Location (City) </label>
                                <input type="text" class="form-control" id="inputCity">
                            </div>
                        </div>
                        <div class="col-md-12 mb-3">
                            <a class="text-white" href="#">Locate me</a>
                        </div>
                        <div class="col-md-6 mb-3">
                            <div class="form-group files">
                                <label>Upload Resume</label>
                                <input type="file" class="form-control" multiple="">
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group files">
                                <label>Upload Portfolio</label>
                                <input type="file" class="form-control" multiple="">
                            </div>
                        </div>
                        <div class="col-md-12 mt-4">
                            <div class="form-btn">
                                <button type="submit" class="btn bg-light">Submit Application</button>
                            </div>    
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</section> 


<style>
.carrerDetails-form .bg-info {
    background-color: #f7f7fa !important;
}
.carrerDetails-form .text-white {
    color: #222 !important;
}   
.carrerDetails-form .form-control {
    height: 43px !important;
    border: none !important;
    font-size: 14px !important;
     border: 1px solid #c2c2c2 !important;
}   
    .conpany_name,
    .location {
        font-size: 13px !important;
    }

    .What_list {
        list-style: disc;
        padding: 0 0 0 30px;
    }

    .What_list_num {
        list-style: decimal;
        padding: 0 0 0 30px;
    }

    .What_list_num li,
    .What_list li {
        font-size: 14px;
    }

    label {
        font-size: 15px;
    }

    form a,
    form button,
    form span {
        font-size: 14px !important;
    }
.files input { 
    padding: 10px 10px;
    text-align: center !important;
    margin: 0;
    width: 100% !important;
} 
.files{ position:relative}
.files:after {  pointer-events: none;
    position: absolute;
    top: 60px;
    left: 0;
    width: 50px;
    right: 0;
    height: 56px;
    content: ""; 
    display: block;
    margin: 0 auto;
    background-size: 100%;
    background-repeat: no-repeat;
} 
/*.files:before {
    position: absolute;
    bottom: 10px;
    left: 0;  pointer-events: none;
    width: 100%;
    right: 0;
    height: 57px;
    content: " or drag it here. ";
    display: block;
    margin: 0 auto;
    color: #2ea591;
    font-weight: 600;
    text-transform: capitalize;
    text-align: center;
} */
.carrerDetails-form h4 {
    font-size: 24px;
    text-transform: uppercase;
    text-align: center;
    margin-top: 40px;
    margin-bottom: 30px !important;
    display: block;
} 
.carrerDetails-form button.btn.bg-light {
    color: #222;
    border: 0;
    padding: 10px 40px; 
    letter-spacing: 0;
    font-size: 15px;
    background: #ddd !important;
    text-transform: uppercase;
}
.carrerDetails-form .form-group label {
    font-size: 14px;
} 
.carrerDetails-form .input-text, .carrerDetails-form .select {
    border: 1px solid #c2c2c2
}
    
@media (max-width:767px) {
.columns .column.main {
    padding: 0 0px;
}
.career-details p {
    font-size: 13px;
}
.What_list_num li, .What_list li {
    font-size: 13px;
}
.carrerDetails-form h4 {
    font-size: 18px; 
    margin-top: 20px;
    margin-bottom: 15px !important; 
} 
.form-btn {
    text-align: center;
}
.carrerDetails-form button.btn.bg-light{
    padding: 10px 18px;
}   
    
    
    
} 
    
    
</style>
