<div class="banner_slider cms-panel">
   <div class="banner"
      style="background-image: url(https://cardeposit.ezmartech.com/media/manage_imagess/c/banner.png);">
      <div class="container-fluid">
         <h1 class="banner_heading text-center">Franchises</h1>
      </div>
   </div>
</div>

<section class="auction_calender pnl_spacing">
        <div class="container">
            <p>Car deposit Auction Calendar is a feature that showcases the dates of all upcoming auctions in the UAE, Oman and Bahrain. This feature will allow you to keep track of all auctions running in the region. You can view the Auction Calendar page
                in different ways including, a calendar view or a list view. The calendar view will display all auctions running on a specific day. The list view will categorize the auctions by location, time or region. The Auction Calendar feature will
                never allow you to miss out on any auction.</p>

            <div class="show_result_form">
                <div class="row">
                    <div class="col-md-7 col-lg-6">
                        <div class="view_link">
                            <ul>
                                <li><a href="#">View</a></li>
                                <li><a href="#"><i class="fa fa-calendar" aria-hidden="true"></i>Calendar</a></li>
                                <li><a href="#"><i class="fa fa-list" aria-hidden="true"></i>List</a></li>
                                <li><a href="#"><i class="fa fa-print" aria-hidden="true"></i>Print</a></li>
                                <li><a href="#"><i class="fa fa-envelope" aria-hidden="true"></i>Email</a></li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
            <div class="auction_calender_table table-responsive">

            </div>
        </div>
    </section>
