<?php 

//$_objectManager = \Magento\Framework\App\ObjectManager::getInstance(); //instance of\Magento\Framework\App\ObjectManager
//$storeManager = $_objectManager->get('Magento\Store\Model\StoreManagerInterface'); 
//$currentStore = $storeManager->getStore();
$baseUrl =$block->getBaseUrl();

?>


<section class="hero-panel">
		<div class="hero-slider">
			<div class="item">
				<div class="hero-contentbox" style="background-image: url(<?php echo $baseUrl ;?>media/hero-banner.jpg);">
					<div class="container">
						<div class="hero-infobox">
							<h1>Best Gift for all Occasions!</h1>
							<a class="shope-btn" href="#">shop now</a>
						</div>
					</div>
				</div>
			</div>
		</div>
	</section>

	<section class="home-productpanel default-panel">
		<div class="container">
			<div class="row">
				<div class="col-md-12">
					<h2 class="top-heading text-center">our products</h2>
					<div class="view-allpanel">
						<div class="view-tagbox">
							<ul class="nav nav-tabs border-0">
								<li><a class="active" href="#flash-sales" data-toggle="tab">Flash Sales </a></li>
								<li><a href="#new-arrival" data-toggle="tab">New Arrival</a></li>
								<li><a href="#trending" data-toggle="tab">Trending</a></li>
								<li><a href="#bestsellers" data-toggle="tab">Best Sellers</a></li>
							</ul>
						</div>
					</div>
				</div>
			</div>
		</div>
		<div class="view-tag_details active" id="flash-sales">
			<div class="slider-allview">
				<div class="item">
					<div class="product-box">
						<a class="product-imgbox" href="#">
							<img src="<?php echo $baseUrl ;?>media/product-1.png" alt="">
						</a>
						<p>Bath and Body Works Frosted Cranberry 3-Wick Candal 411g...</p>
						<span class="price">AED65.99</span>
						
						
					</div>
					<div class="product-box">
						<a class="product-imgbox" href="#">
							<img src="<?php echo $baseUrl ;?>media/product-1.png" alt="">
						</a>
						<p>Bath and Body Works Frosted Cranberry 3-Wick Candal 411g...</p>
						<span class="price">AED65.99</span>

					</div>
				</div>
				<div class="item">
					<div class="product-box">
						<a class="product-imgbox" href="#">
							<img src="<?php echo $baseUrl ;?>media/product-1.png" alt="">
						</a>
						<p>Bath and Body Works Frosted Cranberry 3-Wick Candal 411g...</p>
						<span class="price">AED65.99</span>
						
					</div>
					<div class="product-box">
						<a class="product-imgbox" href="#">
							<img src="<?php echo $baseUrl ;?>media/product-1.png" alt="">
						</a>
						<p>Bath and Body Works Frosted Cranberry 3-Wick Candal 411g...</p>
						<span class="price">AED65.99</span>
					</div>
				</div>
				<div class="item">
					<div class="product-box">
						<a class="product-imgbox" href="#">
							<img src="<?php echo $baseUrl ;?>media/product-1.png" alt="">
						</a>
						<p>Bath and Body Works Frosted Cranberry 3-Wick Candal 411g...</p>
						<span class="price">AED65.99</span>
					</div>
					<div class="product-box">
						<a class="product-imgbox" href="#">
							<img src="<?php echo $baseUrl ;?>media/product-1.png" alt="">
						</a>
						<p>Bath and Body Works Frosted Cranberry 3-Wick Candal 411g...</p>
						<span class="price">AED65.99</span>
					</div>
				</div>
				<div class="item">
					<div class="product-box">
						<a class="product-imgbox" href="#">
							<img src="<?php echo $baseUrl ;?>media/product-1.png" alt="">
						</a>
						<p>Bath and Body Works Frosted Cranberry 3-Wick Candal 411g...</p>
						<span class="price">AED65.99</span>
					</div>
					<div class="product-box">
						<a class="product-imgbox" href="#">
							<img src="<?php echo $baseUrl ;?>media/product-1.png" alt="">
						</a>
						<p>Bath and Body Works Frosted Cranberry 3-Wick Candal 411g...</p>
						<span class="price">AED65.99</span>
					</div>
				</div>
				<div class="item">
					<div class="product-box">
						<a class="product-imgbox" href="#">
							<img src="<?php echo $baseUrl ;?>media/product-1.png" alt="">
						</a>
						<p>Bath and Body Works Frosted Cranberry 3-Wick Candal 411g...</p>
						<span class="price">AED65.99</span>
					</div>
					<div class="product-box">
						<a class="product-imgbox" href="#">
							<img src="<?php echo $baseUrl ;?>media/product-1.png" alt="">
						</a>
						<p>Bath and Body Works Frosted Cranberry 3-Wick Candal 411g...</p>
						<span class="price">AED65.99</span>
					</div>
				</div>
			</div>
		</div>
		<div class="view-tag_details" id="new-arrival">
			<h2 class="text-center">Coming Soon</h2>
		</div>
		<div class="view-tag_details" id="trending">
			<h2 class="text-center">Coming Soon2</h2>
		</div>
		<div class="view-tag_details" id="bestsellers">
			<h2 class="text-center">Coming Soon3</h2>
		</div>

	</section>

	<section class="trending-brandspanel default-panel">
		<div class="container-fluid">
			<h2 class="top-heading text-center">Trending Brands</h2>
			<div class="brands-slider">
				<div class="item">
					<div class="brands-box">
						<img src="<?php echo $baseUrl ;?>media/brands-logo.png" alt="">
					</div>
				</div>
				<div class="item">
					<div class="brands-box">
						<img src="<?php echo $baseUrl ;?>media/brands-logo.png" alt="">
					</div>
				</div>
				<div class="item">
					<div class="brands-box">
						<img src="<?php echo $baseUrl ;?>media/brands-logo.png" alt="">
					</div>
				</div>
				<div class="item">
					<div class="brands-box">
						<img src="<?php echo $baseUrl ;?>media/brands-logo.png" alt="">
					</div>
				</div>
				<div class="item">
					<div class="brands-box">
						<img src="<?php echo $baseUrl ;?>media/brands-logo.png" alt="">
					</div>
				</div>
			</div>
		</div>
	</section>

	<section class="homeblog-panel default-panel">
		<div class="container-fluid">
			<div class="row">
				<div class="col-md-4">
					<div class="homeblog-imgbox">
						<a href="#"><img src="<?php echo $baseUrl ;?>media/blog-img.png" alt=""></a>
					</div>
				</div>
				<div class="col-md-4">
					<div class="homeblog-imgbox">
						<a href="#"><img src="<?php echo $baseUrl ;?>media/blog-img2.png" alt=""></a>
					</div>
				</div>
				<div class="col-md-4">
					<div class="homeblog-imgbox">
						<a href="#"><img src="<?php echo $baseUrl ;?>media/blog-img3.png" alt=""></a>
					</div>
				</div>
			</div>
		</div>
	</section>

<div class="footer-strip">
			<div class="container">
				<div class="row">
					<div class="col-md-4">
						<div class="footer-stripbox">
							<img src="<?php echo $baseUrl ;?>media/worldwide-shipping.png" alt="">
							<p><strong>Worldwide Shipping</strong>Special financing and earn rewwards.</p>
						</div>
					</div>
					<div class="col-md-4">
						<div class="footer-stripbox">
							<img src="<?php echo $baseUrl ;?>media/guarantee-icon.png" alt="">
							<p><strong>30 Days Guarantee</strong>30-day free return policy.</p>
						</div>
					</div>
					<div class="col-md-4">
						<div class="footer-stripbox">
							<img src="<?php echo $baseUrl ;?>media/secured-icon.png" alt="">
							<p><strong>Secured Payments</strong>We accept all majoi credit cards.</p>
						</div>
					</div>
				</div>
			</div>
		</div>
