<?php $gallery_data = $block->getGalleryData();?>
<?php //echo "<pre>"; print_r($gallery_data); echo "</pre>";?>
<section class="media-gallery">
    <div class="gallerybanner-img">
        <img src="/media/<?= $gallery_data['gallery_banner']?>" alt="">
        <div class="topBanner-text">
            <h1><?= $gallery_data['title']?></h1>
            <p><?= $gallery_data['description']?></p>
        </div>
    </div>
</section>

<div class="media-gallery-details">
    <div class="container">
        <?php $i=0;foreach ($block->getAllImageFromGalleries() as $image): ?>
            <?php if($i++%2!=1):?>
                <div class="row mob-dir">
                    <div class="col-lg-6 col-md-6 col-sm-12">
                        <div class="details-img"> <img src="<?php echo $block->getMediaUrl() . $image['image'] ?>" alt=""/>
                        </div>
                    </div>
                    <div class="col-lg-6 col-md-6 col-sm-12">
                        <div class="headtitle-coll">
                            <h3><?= $image['title']?></h3>
                            <p><?= $image['description']?></p>
                            <div class="product-btn1"> <a href="<?= $image['product_link']?>" class="btn"><?= __('Shop the look')?></a> </div>
                        </div>
                    </div>
                </div>
            <?php else:?>
                <div class="row mob-dir">
                    <div class="col-lg-6 col-md-6 col-sm-12">
                        <div class="headtitle-coll">
                            <h3><?= $image['title']?></h3>
                            <p><?= $image['description']?></p>
                            <div class="product-btn1"> <a href="<?= $image['product_link']?>" class="btn"><?= __('Shop the look')?></a> </div>
                        </div>
                    </div>
                    <div class="col-lg-6 col-md-6 col-sm-12 order-one">
                        <div class="details-img"> <img src="<?php echo $block->getMediaUrl() . $image['image'] ?>" alt=""/>
                        </div>
                    </div>
                </div>
            <?php endif;?>
        <?php endforeach; ?>
    </div>
</div>
<style>
    .breadcrumbs {
        display: none;
    }

    main#maincontent {
        padding: 0px 0px !important;
    }

    .gallerybanner-img img,
    .details-img img {
        width: 100%;
        display: block;
    }

    .cms-media-gallery main#maincontent {
        padding: 0 0px !important;
    }

    .media-gallery-details .row {
        display: flex;
        align-items: center;
    }

    .topBanner-text {
        position: absolute;
        top: 50%;
        left: 50%;
        transform: translate(-50%, -50%);
    }

    section.media-gallery {
        position: relative;
        margin-bottom: 40px;
    }

    section.media-gallery:after {
        content: "";
        display: block;
        position: absolute;
        top: 0;
        left: 0;
        height: 100%;
        width: 100%;
        background: linear-gradient(to bottom, rgba(0, 0, 0, .12) 0%, rgba(0, 0, 0, .12) 100%);
    }

    .topBanner-text h1 {
        font-weight: 600;
        font-size: 39px;
        padding: 0;
        text-transform: uppercase;
        margin-bottom: 20px;
        text-align: center;
        color: #0d4c26;
        line-height: 36px;
    }

    .topBanner-text p {
        font-size: 17px;
        color: #000;
        margin-bottom: 20px;
        text-align: center;
    }

    .headtitle-coll h3 {
        text-align: center;
        font-size: 26px;
        font-weight: 600;
        line-height: 25px;
        margin-bottom: 20px;
    }

    .headtitle-coll {
        width: 90%;
        margin: 0 auto;
    }

    .headtitle-coll p {
        text-align: center;
        font-size: 14px;
        line-height: 24px;
        margin-bottom: 10px;
        color: #000;
    }

    .product-btn1 a.btn {
        padding: 12px 28px;
        font-size: 12px;
        display: inline-block;
        text-align: center;
        border: 1px solid #424a54;
        color: #424a54;
        line-height: 15px;
        text-transform: uppercase;
    }

    .product-btn1 {
        text-align: center;
        margin-top: 20px;
        display: block;
    }


    @media (max-width:767px) {
        .columns .column.main {
            padding: 0 0px;
        }

        .topBanner-text {
            position: static;
            top: 0;
            left: unset;
            transform: unset;
            padding: 2% 1%;
        }

        .topBanner-text h1 {
            font-size: 26px;
            margin-bottom: 5px;
            line-height: 24px;
            margin-top: 10px;
        }

        .topBanner-text p {
            font-size: 15px;
            margin-bottom: 10px;
        }

        .media-gallery-details .row {
            flex-direction: row;
        }

        .order-one {
            order: -1;
        }

        .headtitle-coll {
            width: 100%;
            margin: 15px auto 40px;
        }

        .headtitle-coll h3 {
            font-size: 23px;
            line-height: 25px;
            margin-bottom: 15px;
        }

        .headtitle-coll p {
            text-align: center;
            font-size: 13px;
            line-height: 21px;
            margin-bottom: 10px;
            color: #000;
        }

        .page-main {
            margin-top: 37px !important;
        }
    }

</style>



<style>
    #popup-modal {
        display: none;
    }

    .popup-image-current {
        width: 500px;
        height: 400px;
    }

    .image-slide-show {
        width: 50px;
        height: 50px;
    }

    .border-for-image {
        border: solid 2px red !important;
    }
</style>