<?php
/**
 * Webkul Software
 *
 * @category Webkul
 * @package Webkul_Walletsystem
 * @author Webkul
 * @copyright Copyright (c) Webkul Software Private Limited (https://webkul.com)
 * @license https://store.webkul.com/license.html
 */
$url = $block->getajaxUrl();
$grandTotal = $block->getGrandTotal();
$viewBlock = $block->getLayout()->createBlock(\Webkul\Walletsystem\Block\Walletsystem::class);
$viewBlock->helper(\Webkul\Walletsystem\Helper\Data::class)->checkWalletproductWithOtherProduct();
?>
<?php
$formData = [
    'grandtotal'   => $grandTotal,
    'ajaxurl'       => $url,
    'wkshippingmethod'    =>  '#shipping-method-buttons-container button.continue'
];
$serializedFormData = $viewBlock->helper(\Magento\Framework\Json\Helper\Data::class)->jsonEncode($formData);
?>
<script type="text/x-magento-init">
    {
        "*": {
            "Wkwalletsystem": <?=/*@noEscape*/ $serializedFormData; ?>
        }
    }
</script>