<section class="hero-panel marketplace-herobanner">
        <div class="hero-slider">
            <div class="item">
                <a href="customer/account/create/">
                    <div class="hero-contentbox" style="background-image: url(media/manage_imagess/h/e/hero-banner_8.jpg);">
                    </div>
                </a>
            </div>
        </div>
    </section>

    <section class="benefits-panel default-panel">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <h2 class="top-heading text-center">Benefits</h2>
                </div>
                <div class="col-lg-4 col-md-6">
                    <div class="Benefits-box p-4 text-center">
                        <img src="https://seller.jebelz.com/skin/frontend/ced/default/dist/img/online-customers.png"
                            class="mx-auto d-block img-fluid">
                        <p class="my-3">Lorem ipsum dolor, sit amet consectetur adipisicing elit.</p>
                    </div>
                </div>
                <div class="col-lg-4 col-md-6">
                    <div class="Benefits-box p-4 text-center">
                        <img src="https://seller.jebelz.com/skin/frontend/ced/default/dist/img/online-customers.png"
                            class="mx-auto d-block img-fluid">
                        <p class="my-3">Lorem ipsum dolor, sit amet consectetur adipisicing elit.</p>
                    </div>
                </div>
                <div class="col-lg-4 col-md-6">
                    <div class="Benefits-box p-4 text-center">
                        <img src="https://seller.jebelz.com/skin/frontend/ced/default/dist/img/online-customers.png"
                            class="mx-auto d-block img-fluid">
                        <p class="my-3">Lorem ipsum dolor, sit amet consectetur adipisicing elit.</p>
                    </div>
                </div>
                <div class="col-lg-4 col-md-6">
                    <div class="Benefits-box p-4 text-center">
                        <img src="https://seller.jebelz.com/skin/frontend/ced/default/dist/img/online-customers.png"
                            class="mx-auto d-block img-fluid">
                        <p class="my-3">Lorem ipsum dolor, sit amet consectetur adipisicing elit.</p>
                    </div>
                </div>
                <div class="col-lg-4 col-md-6">
                    <div class="Benefits-box p-4 text-center">
                        <img src="https://seller.jebelz.com/skin/frontend/ced/default/dist/img/online-customers.png"
                            class="mx-auto d-block img-fluid">
                        <p class="my-3">Lorem ipsum dolor, sit amet consectetur adipisicing elit.</p>
                    </div>
                </div>
                <div class="col-lg-4 col-md-6">
                    <div class="Benefits-box p-4 text-center">
                        <img src="https://seller.jebelz.com/skin/frontend/ced/default/dist/img/online-customers.png"
                            class="mx-auto d-block img-fluid">
                        <p class="my-3">Lorem ipsum dolor, sit amet consectetur adipisicing elit.</p>
                    </div>
                </div>
            </div>
        </div>
    </section>

    <section class="benefits-listpanel default-panel">
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-12">
                    <h2 class="top-heading text-center text-white">Selling on QaderExpress  is easy</h2>
                    <div class="point-list-benifit">
                        <ul>
                            <li>Emirates ID</li>
                            <li>Passport</li>
                            <li>VAT Registration</li>
                            <li>Bank Account</li>
                            <li>Trading License</li>
                            <li>Office Address</li>
                            <li>1 Product</li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </section>

    <div class="how-it-works default-panel">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <h2 class="top-heading text-center mb-3">How It Works</h2>
                    <h4 class="text-center mb-5">Doing Online Business On QaderExpress  is Simple</h4>
                </div>
            </div>


            <div class="row">
                <div class="col-md-1 col-12"></div>
                <div class="col-md-4 col-12 img-margin-top-howitwork">
                    <img src="media/marketplace/icon/icon-register-yourself.png"
                        class="img-fluid d-block text-center mx-auto float-right">
                </div>
                <div class="col-md-2 col-12 d-md-block d-none">
                    <img src="https://seller.jebelz.com/skin/frontend/ced/default/dist/img/line1.png"
                        class="img-fluid d-block text-center mx-auto">
                </div>
                <div class="col-md-4 col-12 how-it-work-des">
                    <h5>Register Yourself</h5>
                </div>
                <div class="col-md-1 col-12"></div>
            </div>

            <div class="row">


                <div class="col-md-1 col-12"></div>
                <div class="col-md-4 col-12 how-it-work-des text-right">
                    <h5>Add Products</h5>
                </div>
                <div class="col-md-2 col-12 d-md-block d-none">
                    <img src="https://seller.jebelz.com/skin/frontend/ced/default/dist/img/line1.png"
                        class="img-fluid d-block text-center mx-auto">
                </div>
                <div class="col-md-4 col-12 img-margin-top-howitwork">
                    <img src="media/marketplace/icon/icon-add-products.png"
                        class="img-fluid d-block text-center mx-auto float-left">
                </div>

                <div class="col-md-1 col-12"></div>
            </div>

            <div class="row">


                <div class="col-md-1 col-12"></div>
                <div class="col-md-4 col-12 img-margin-top-howitwork">
                    <img src="media/marketplace/icon/icon-start-selling.png"
                        class="img-fluid d-block text-center mx-auto float-right">
                </div>
                <div class="col-md-2 col-12 d-md-block d-none">
                    <img src="https://seller.jebelz.com/skin/frontend/ced/default/dist/img/line1.png"
                        class="img-fluid d-block text-center mx-auto">
                </div>
                <div class="col-md-4 col-12 how-it-work-des">
                    <h5>Start Selling</h5>
                </div>
                <div class="col-md-1 col-12"></div>
            </div>

            <div class="row">


                <div class="col-md-1 col-12"></div>
                <div class="col-md-4 col-12 how-it-work-des text-right">
                    <h5>Generate Revenues</h5>
                </div>
                <div class="col-md-2 col-12 d-md-block d-none">
                    <img src="https://seller.jebelz.com/skin/frontend/ced/default/dist/img/line1.png"
                        class="img-fluid d-block text-center mx-auto">
                </div>
                <div class="col-md-4 col-12 img-margin-top-howitwork">
                    <img src="media/marketplace/icon/icon-collect-revenues.png"
                        class="img-fluid d-block text-center mx-auto float-left">
                </div>

                <div class="col-md-1 col-12"></div>
            </div>

            <div class="row">
                <div class="col-md-12">
                    <div class="register-btns-normal text-center">
                        <a class="shope-btn" href="/manage/seller/register">Register Now</a>
                    </div>
                </div>
            </div>

        </div>
    </div>
	

	
<?php
/**
 * Webkul Software.
 *
 * @category  Webkul
 * @package   Webkul_Marketplace
 * @author    Webkul
 * @copyright Copyright (c) Webkul Software Private Limited (https://webkul.com)
 * @license   https://store.webkul.com/license.html
 */
$helper = $this->helper(\Webkul\Marketplace\Helper\Data::class);
// $pageLayout  =    $helper->getPageLayout();
// if ($pageLayout == 1) {
//     echo $block->getChildHtml('landingPagelayout1');
// } elseif ($pageLayout == 2) {
//     echo $block->getChildHtml('landingPagelayout2');
// } else {
//     echo $block->getChildHtml('landingPagelayout3');
// }



?>

