<div class="container">
    <div class="row">
        <div class="col-lg-12">
            <div class="contact-section-title">BRANCHES</div>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-6">
            <div class="accordion">
                <div class="accordion__header is-active">
                    <h2> Management Office </h2>
                    <span class="accordion__toggle"></span>
                </div>
                <div class="accordion__body is-active">
                    <div class="storelocatorlist">
                        <h6>Dubai, U.A.E. Office</h6>
                        <p>Administration Office: Al Qusais Industrial<br>Area 3, P.O.Box : 87652, Dubai, U.A.E.<br>Mon - Fri : 0900am to 0600pm<br> +91 11 4527 9900 <br> support@example.com</p>
                        <p class="loc-list"><a href="" target="_blank"><img width="20px" height="20px" class="" src="/media/wysiwyg/map-icon.svg" alt="Map Icon"></a></p>
                    </div>
                </div>


                <div class="accordion__header">
                    <h2> Festival City Branch </h2>
                    <span class="accordion__toggle"></span>
                </div>
                <div class="accordion__body">
                    <div class="storelocatorlist">
                        <h6>Dubai, U.A.E. Office</h6>
                        <p>Administration Office: Al Qusais Industrial<br>Area 3, P.O.Box : 87652, Dubai, U.A.E.<br>Mon - Fri : 0900am to 0600pm<br> +91 11 4527 9900 <br> support@example.com</p>
                        <p class="loc-list"><a href="" target="_blank"><img width="20px" height="20px" class="" src="/media/wysiwyg/map-icon.svg" alt="Map Icon"></a></p>
                    </div>
                </div>


                <div class="accordion__header">
                    <h2> Festival City Branch </h2>
                    <span class="accordion__toggle"></span>
                </div>
                <div class="accordion__body">
                    <div class="storelocatorlist">
                        <h6>Dubai, U.A.E. Office</h6>
                        <p>Administration Office: Al Qusais Industrial<br>Area 3, P.O.Box : 87652, Dubai, U.A.E.<br>Mon - Fri : 0900am to 0600pm<br> +91 11 4527 9900 <br> support@example.com</p>
                        <p class="loc-list"><a href="" target="_blank"><img width="20px" height="20px" class="" src="/media/wysiwyg/map-icon.svg" alt="Map Icon"></a></p>
                    </div>
                </div>

                <div class="accordion__header">
                    <h2> Festival City Branch </h2>
                    <span class="accordion__toggle"></span>
                </div>
                <div class="accordion__body">
                    <div class="storelocatorlist">
                        <h6>Dubai, U.A.E. Office</h6>
                        <p>Administration Office: Al Qusais Industrial<br>Area 3, P.O.Box : 87652, Dubai, U.A.E.<br>Mon - Fri : 0900am to 0600pm<br> +91 11 4527 9900 <br> support@example.com</p>
                        <p class="loc-list"><a href="" target="_blank"><img width="20px" height="20px" class="" src="/media/wysiwyg/map-icon.svg" alt="Map Icon"></a></p>
                    </div>
                </div>

            </div>
        </div>
        <div class="col-lg-6">
            <div class="accordion">
                <div class="accordion__header is-active">
                    <h2> Management Office </h2>
                    <span class="accordion__toggle"></span>
                </div>
                <div class="accordion__body is-active">
                    <div class="storelocatorlist">
                        <h6>Dubai, U.A.E. Office</h6>
                        <p>Administration Office: Al Qusais Industrial<br>Area 3, P.O.Box : 87652, Dubai, U.A.E.<br>Mon - Fri : 0900am to 0600pm<br> +91 11 4527 9900 <br> support@example.com</p>
                        <p class="loc-list"><a href="" target="_blank"><img width="20px" height="20px" class="" src="/media/wysiwyg/map-icon.svg" alt="Map Icon"></a></p>
                    </div>
                </div>
                <div class="accordion__header">
                    <h2> Festival City Branch </h2>
                    <span class="accordion__toggle"></span>
                </div>
                <div class="accordion__body">
                    <div class="storelocatorlist">
                        <h6>Dubai, U.A.E. Office</h6>
                        <p>Administration Office: Al Qusais Industrial<br>Area 3, P.O.Box : 87652, Dubai, U.A.E.<br>Mon - Fri : 0900am to 0600pm<br> +91 11 4527 9900 <br> support@example.com</p>
                        <p class="loc-list"><a href="" target="_blank"><img width="20px" height="20px" class="" src="/media/wysiwyg/map-icon.svg" alt="Map Icon"></a></p>
                    </div>
                </div>

                <div class="accordion__header">
                    <h2> Festival City Branch </h2>
                    <span class="accordion__toggle"></span>
                </div>
                <div class="accordion__body">
                    <div class="storelocatorlist">
                        <h6>Dubai, U.A.E. Office</h6>
                        <p>Administration Office: Al Qusais Industrial<br>Area 3, P.O.Box : 87652, Dubai, U.A.E.<br>Mon - Fri : 0900am to 0600pm<br> +91 11 4527 9900 <br> support@example.com</p>
                        <p class="loc-list"><a href="" target="_blank"><img width="20px" height="20px" class="" src="/media/wysiwyg/map-icon.svg" alt="Map Icon"></a></p>
                    </div>
                </div>

                <div class="accordion__header">
                    <h2> Festival City Branch </h2>
                    <span class="accordion__toggle"></span>
                </div>
                <div class="accordion__body">
                    <div class="storelocatorlist">
                        <h6>Dubai, U.A.E. Office</h6>
                        <p>Administration Office: Al Qusais Industrial<br>Area 3, P.O.Box : 87652, Dubai, U.A.E.<br>Mon - Fri : 0900am to 0600pm<br> +91 11 4527 9900 <br> support@example.com</p>
                        <p class="loc-list"><a href="" target="_blank"><img width="20px" height="20px" class="" src="/media/wysiwyg/map-icon.svg" alt="Map Icon"></a></p>
                    </div>
                </div>

            </div>

        </div>
    </div>
</div>

 

<script>
    require([
        'jquery'
    ], function($, $t) {
        // Set the date we're counting down to
        $(document).ready(function() {
            $('.accordion__header').click(function(e) {
                e.preventDefault();
                var currentIsActive = $(this).hasClass('is-active');
                $(this).parent('.accordion').find('> *').removeClass('is-active');
                if (currentIsActive != 1) {
                    $(this).addClass('is-active');
                    $(this).next('.accordion__body').addClass('is-active');
                }
            });

        });
    });

</script>


<style>
    .cms-branches .container {
        max-width: 1300px;
        width: 100%;
    }

    .cms-branches .page-title-wrapper {
        display: none;
    }

    .accordion__header {
        padding: 1.4em;
        background-color: #0d4c26;
        margin-top: 15px;
        display: flex;
        justify-content: space-between;
        align-items: center;
        cursor: pointer;
    }

    .accordion__header>* {
        margin-top: 0;
        margin-bottom: 0;
        font-size: 16px;
        color: #fff;
    }

    .accordion__header>h2 {
        color: #fff;
    }

    .accordion__header.is-active {
        background-color: #b6b096;
        color: #000;
    }

    .accordion__toggle {
        margin-left: 10px;
        height: 3px;
        background-color: #fff;
        width: 13px;
        display: block;
        position: relative;
        flex-shrink: 1;
        border-radius: 2px;
    }

    .accordion__toggle::before {
        content: "";
        width: 3px;
        height: 13px;
        display: block;
        background-color: #fff;
        position: absolute;
        top: -5px;
        left: 5px;
        border-radius: 2px;
    }

    .is-active .accordion__toggle {
        background-color: #fff;
    }

    .is-active .accordion__toggle::before {
        display: none;
    }

    .accordion__body {
        display: none;
        padding: 1em;
        border: 1px solid #ccc;
        border-top: 0;
    }

    .accordion__body.is-active {
        display: block;
    }

    .storelocatorlist {
        background: #f3f2f2;
        padding-top: 30px;
        padding-bottom: 30px;
    }

    .storelocatorlist h6 {
        font-size: 18px;
        margin-bottom: 15px;
    }

    .storelocatorlist h6,
    .storelocatorlist p {
        text-align: center;
    }

    section.storelocator-wrap p {
        font-size: 12px;
        font-family: "Gotham HTF Book";
        text-transform: uppercase;
        letter-spacing: .05em;
        margin-top: 10px;
        line-height: 20px;
    }

    .storelocatorlist h6,
    .storelocatorlist p {
        text-align: center;
    }

    .storelocatorlist p img {
        width: 28px;
        margin: 0 auto;
        margin-bottom: 0;
        padding: 0 4px;
    }

    .cms-branches .container {
        max-width: 1300px;
        width: 100%;
    }
.contact-section-title {
    font-size: 26px;
    text-align: left;
    font-weight: 700;
}
    
</style>
