<div class="sub-content">
    <div class="vertical-menu-wrapper">
        <div class="tab">

            <ul class="nav nav-tabs">
                <li class="nav-item "> <a class="active" data-toggle="tab" href="#Sweets">Sweets</a></li>
                <li class="nav-item"><a data-toggle="tab" href="#FreshProducts">Fresh Products</a></li>
        </div>

        <div class="right-menu-wrapper tab-content">
            <div id="Sweets" class="tab-pane active">
                <div class="category-navbox">
                    <h3><a href="">Sweets</a></h3>
                    <div class="category-navsub">
                        <ul>
                            <li>
                                <h4>Baklava</h4>
                            </li>
                            <li><a href="#">Mixed Baklava</a></li>
                            <li><a href="#">Mabroma</a></li>
                            <li><a href="#">Mixed Oush Albolbol</a></li>
                            <li><a href="#">Kol w Shkor</a></li>
                            <li><a href="#">Baloriah</a></li>
                            <li><a href="#">Cashew Fingers</a></li>
                            <li><a href="#">Walnut Fingers</a></li>
                        </ul>
                    </div>
                    <div class="category-navsub">
                        <ul>
                            <li>
                                <h4>Nawashif</h4>
                            </li>
                            <li><a href="#">Mixed Nwashef</a></li>
                            <li><a href="#">Brazek</a></li>
                            <li><a href="#">Ghuraiba</a></li>
                            <li><a href="#">Walnut Twetat</a></li>
                            <li><a href="#">Ajweh</a></li>
                            <li><a href="#">Ajwa Tablets With Honey</a></li>
                            <li><a href="#">Pistachio Maamoul</a></li>
                        </ul>
                    </div>
                    <div class="category-navsub">
                        <ul>
                            <li>
                                <h4>Mamoul</h4>
                            </li>
                            <li><a href="#">Walnut Twetat</a></li>
                            <li><a href="#">Ajweh</a></li>
                            <li><a href="#">Ajwah Tablets with Honey</a></li>
                            <li><a href="#">Pistachio Maamoul</a></li>
                        </ul>
                    </div>
                    <div class="category-navsub">
                        <ul>
                            <li>
                                <h4>Healthy Products</h4>
                            </li>
                            <li><a href="#">Mixed Baklava Diet</a></li>
                            <li><a href="#">Honey</a></li>
                            <li><a href="#">Mixed Baklava with honey</a></li>
                        </ul>
                    </div>
                    <div class="category-navsub">
                        <ul>
                            <li>
                                <h4>Ice Cream</h4>
                            </li>
                            <li><a href="#">Ice Cream with Pistachio</a></li>
                            <li><a href="#">Ice Cream Cup</a></li>
                            <li><a href="#">Plain Ice Cream</a></li>
                        </ul>
                    </div>
                    <div class="category-navsub">
                        <ul>
                            <li>
                                <h4><a href="#">Chocolate</a></h4>
                            </li>
                        </ul>
                    </div>
                    <div class="category-navsub">
                        <ul>
                            <li>
                                <h4><a href="#">Nougat</a></h4>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>

            <div id="FreshProducts" class="tab-pane">
                <div class="category-navbox">
                    <h3><a href="#">Fresh Products</a></h3>
                    <div class="category-navsub">
                        <ul>
                            <li>
                                <h4>Kunafa</h4>
                            </li>
                            <li><a href="#">Rugh Kunafa with Cream</a></li>
                            <li><a href="#">Soft Kunafa with Cheese</a></li>
                            <li><a href="#">Rugh Kunafa with Cream</a></li>
                            <li><a href="#">Soft Kunafa with Cream</a></li>
                            <li><a href="#">Kunafa with mixed nuts</a></li>
                        </ul>
                    </div>
                    <div class="category-navsub">
                        <ul>
                            <li>
                                <h4>Madluka</h4>
                            </li>
                            <li><a href="#">Madluka with Cream</a></li>
                        </ul>
                    </div>
                    <div class="category-navsub">
                        <ul>
                            <li>
                                <h4>Ghuraiba</h4>
                            </li>
                            <li>
                                <h4>Nammoura with Cream</h4>
                            </li>
                            <li>
                                <h4>Faisaliah</h4>
                            </li>
                        </ul>
                    </div>
                    <div class="category-navsub">
                        <ul>
                            <li>
                                <h4>Katayef</h4>
                            </li>
                            <li><a href="#">Katayef with Cream</a></li>
                            <li><a href="#">Katayef with Walnut</a></li>
                        </ul>
                    </div>
                    
                    <div class="category-navsub">
                        <ul>
                            <li>
                                <h4>Warbat</h4>
                            </li>
                            <li><a href="#">Warbat with Cream</a></li>
                            <li><a href="#">Warbat with Pistachio</a></li>
                        </ul>
                    </div>
                    <div class="category-navsub">
                        <ul>
                            <li>
                                <h4>Harissa</h4>
                            </li>
                            <li><a href="#">Harissa with Pistachio</a></li>
                            <li><a href="#">Harissa with Almond</a></li>
                        </ul>
                    </div>
                    <div class="category-navsub">
                        <ul>
                            <li>
                                <h4>Halawa with Cheese</h4>
                            </li>
                        </ul>
                    </div>
                    <div class="category-navsub">
                        <ul>
                            <li>
                                <h4>Cream (Qashta)</h4>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>

    </div>
</div>