<ul class="footer-cmslimkbox">
    <li><a href="{{store direct_url=''}}?___store=default">Abu Dhabi</a></li>
    <li><a href="{{store direct_url=''}}?___store=default">Dubai</a></li>
    <li><a href="{{store direct_url=''}}?___store=sh_en">Sharjah</a></li>
    <li><a href="{{store direct_url=''}}?___store=default">North Emirates</a></li> 
    <li class='bounceInDown'>
        <ul>
            <li class='sub-menu1'><a href="javascript:void(0);">Store &nbsp;&nbsp;<div class='fa fa-caret-down right'></div></a>
                <ul>
                    <li><a href="{{store direct_url=''}}?___store=us_en">International</a></li>
                    <li><a href="{{store direct_url=''}}?___store=default">Domestic</a></li>
                    <li><a href="{{store direct_url=''}}?___store=tr_en">Turkey</a></li>
                </ul>
            </li>
        </ul>
    </li>
</ul>